version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=abril_user
      - POSTGRES_PASSWORD=abril_pass
      - POSTGRES_DB=abril_db
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  backend:
    build: ./backend
    env_file: ./backend/.env
    depends_on:
      - db
    ports:
      - '5000:5000'

  frontend:
    build: ./frontend
    ports:
      - '3000:3000'

volumes:
  db_data:
